sudo: false
language: php

branches:
  only:
      - master

env:
    global:
        - CHECK_PHP_SYNTAX="no"
        - ENABLE_CODE_COVERAGE="no"
        - COMPOSER_FLAGS=""

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: ENABLE_CODE_COVERAGE="yes"
        - php: 7.1
          env: CHECK_PHP_SYNTAX="yes"
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - if [[ "$ENABLE_CODE_COVERAGE" != "yes" ]]; then phpenv config-rm xdebug.ini || true; fi;

install:
    - composer update --prefer-dist --no-interaction --optimize-autoloader --prefer-stable --no-progress $COMPOSER_FLAGS
    - if [[ "$ENABLE_CODE_COVERAGE" == "yes" ]]; then composer require --dev satooshi/php-coveralls; fi

script:
    - if [[ "$ENABLE_CODE_COVERAGE" == "yes" ]]; then phpunit --coverage-text --coverage-clover build/logs/clover.xml; else phpunit; fi;
    - if [[ "$CHECK_PHP_SYNTAX" == "yes" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --dry-run --no-interaction --diff --path-mode=intersection; fi;

after_success:
    - if [[ "$ENABLE_CODE_COVERAGE" == "yes" ]]; then php vendor/bin/coveralls -v; fi;
